### ISSUE TITLE
Solution to all the issues

### ISSUE THREAD

**Issue by davidperis92** [gabrielgrant/django-multiforloop#6]
### -Python 2:

Add to pip requirements.py django-multiforloop-patched >= 0.2.0
### -Python 3:

1 ->  Copy multiforloop/templatetags to a templatetags folder in your project.

2 -> replace **from itertools import izip_longest** with **from itertools import zip_longest**
       replace **from django.template.base import Library** with **from django import template**
       replace **register = Library()** with **register = template.Library()**

**Comment by aarcro** [comment]
I found django-multiforloop-patched, but it's not working on python 2.7 Djanog 1.9:

> django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'multiforloop.templatetags.multifor': cannot import name Library

**Comment by J-a-n-u-s** [comment]
David, thanks for making this little gem. I had the same problem as others re the templatetags folder. I manually copied the contents it to` <virtualenv>/lib/python3.6/site-packages/multiforloop/templatetags` 
I imagine your solution above is also effective albeit with a quick code mod.
I believe though if you edit your `setup.py` as mentioned [here](https://stackoverflow.com/questions/33859550/python-setuptools-package-data-pip-fails-on-subfolders) to include package_date like:
```
from distutils.core import setup

setup(
    name='django-multiforloop',
    version='0.2.0',
    packages=['multiforloop',],
    author='Gabriel Grant',
    author_email='g@briel.ca',
    license='LGPL',
    long_description=open('README').read(),
    url='http://github.org/gabrielgrant/django-multiforloop/',
    package_data = {
        "multiforloop": ["templatetags/*",]
    }
)
```

OR create a `MANIFEST.in` containing:
`include multiforloop/templatetags/*.*`

it should prevent this hiccup for others.

**Comment by gabrielgrant** [comment]
Thanks for the fix list! I believe all these issues were addressed a while ago by @r3m0t and are up on PyPI, so going to close this issue
